language: python
python:
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7"
  - "3.7-dev" # 3.7 development branch
  - "3.8"
  - "3.8-dev"
  - "nightly"
# command to install dependencies
install: "pip install pymods requests bs4"
# command to run tests
script: py.test citrus/tests/*
notifications:
    email: 
        on_success: change
        on_failure: change
